spring:
  devtools:
    restart:
      enabled: true
  servlet:
    multipart:
      max-file-size: 8MB

logging:
  level:
    root: info
  file:
    name: /log/demo-knife4j.log

#生产环境关闭API文档
#springdoc:
#  api-docs:
#    enabled: false
#
#knife4j:
#  enable: true
#  production: true
