spring:
  devtools:
    restart:
      enabled: true
  servlet:
    multipart:
      max-file-size: 4GB
      max-request-size: 4GB

logging:
  level:
    root: info
  file:
    name: /log/demo-knife4j.log

#生产环境关闭文档
#knife4j:
#  enable: true
#  production: true
#
#springdoc:
#  api-docs:
#    enabled: false
