spring:
  devtools:
    restart:
      enabled: true
  servlet:
    multipart:
      max-file-size: 4GB
      max-request-size: 4GB

elasticsearch:
  uri: http://127.0.0.1:9200

logging:
  level:
    root: info
  file:
    name: /log/demo-elastic-search.log
