spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 4GB
      max-request-size: 4GB
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 10s

#server:
#  compression:
#    enabled: true
#  servlet:
#    context-path: /api
#  port: 443
#  ssl:
#    key-store: classpath:404z.cn.jks
#    key-store-password: ChengKai1998!
#    key-store-type: JKS

tiny-token:
  prefix: tinytoken
  timeout: 2592000

logging:
  file:
    name: /log/demo-base.log
