spring:
  devtools:
    restart:
      enabled: true
  servlet:
    multipart:
      max-file-size: 4GB
      max-request-size: 4GB
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 10s

#server:
#  port: 8081

tiny-task:
  prefix: tinytask
  timeout: 5

logging:
  level:
    root: info
  file:
    name: /log/demo-tiny-task.log
