spring:
  devtools:
    restart:
      enabled: true
  servlet:
    multipart:
      max-file-size: 8MB

mqtt:
  uri: tcp://127.0.0.1:1883
  connection-timeout: 30
  keep-alive-interval: 60
  clean-session: true
  automatic-reconnect: true

logging:
  level:
    root: info
  file:
    name: /log/demo-mqtt.log
