spring:
  devtools:
    restart:
      enabled: true
  servlet:
    multipart:
      max-file-size: 4GB
      max-request-size: 4GB

influx:
  url: http://localhost:8086
  username: admin
  password: chengkai

logging:
  level:
    root: info
  file:
    name: /log/demo-influxdb.log
