spring:
  devtools:
    restart:
      enabled: true
  servlet:
    multipart:
      max-file-size: 4GB
      max-request-size: 4GB

influx:
  url: http://localhost:8086
  username: root
  password: influxdb
#  token: o9HyV0S7GJGZBh8scklSFd5oNqNgMH5qHdCHC45gF0pPlAwJvIgco9hjXHx5D1A6_wnB2F_vWIzXGrKsa-GTkw==
  org: influx
  bucket: db

logging:
  level:
    root: info
  file:
    name: /log/demo-influxdb.log
