spring:
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 10s

sa-token:
  is-log: true

logging:
  level:
    root: info
    com.demo.mapper: trace
