spring:
  devtools:
    restart:
      enabled: true
  servlet:
    multipart:
      max-file-size: 4GB
      max-request-size: 4GB
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 60000
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: demo2
      # username:
      # password:
      auto-index-creation: true
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 10s

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.demo.entity.po,com.demo.entity.vo
  configuration:
    map-underscore-to-camel-case: true

tiny-token:
  prefix-header: token
  prefix-redis: tinytoken
  timeout: 2592000

id:
  machine-id: 0
  machine-bits: 8
  sequence-bits: 12

ip2region:
  resource-path: /file/ip2region/ip2region.zdb

logging:
  level:
    root: info
    com.demo.mapper: trace
  file:
    name: /log/demo-dynamic-route.log

#生产环境关闭API文档
#springdoc:
#  api-docs:
#    enabled: false
#
#knife4j:
#  enable: true
#  production: true
