spring:
  devtools:
    restart:
      enabled: true
  servlet:
    multipart:
      max-file-size: 4GB
      max-request-size: 4GB
  mail:
    host: smtp.qq.com
    username: 1416978277@qq.com
    password: password

logging:
  level:
    root: info
  file:
    name: /log/demo-mail.log
