spring:
  devtools:
    restart:
      enabled: true
  servlet:
    multipart:
      max-file-size: 4GB
      max-request-size: 4GB
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    root: info
  file:
    name: /log/demo-websocket-cluster.log
