spring:
  devtools:
    restart:
      enabled: true
  servlet:
    multipart:
      max-file-size: 4GB
      max-request-size: 4GB
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 10s

tiny-token:
  header: token
  prefix: tinytoken
  timeout: 2592000

logging:
  level:
    root: info
  file:
    name: /log/demo-tiny-token.log
