spring:
  devtools:
    restart:
      enabled: true
  servlet:
    multipart:
      max-file-size: 4GB
      max-request-size: 4GB
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://127.0.0.1:27017/demo

logging:
  level:
    root: info
  file:
    name: /log/demo-mongodb.log
