spring:
  devtools:
    restart:
      enabled: true
  servlet:
    multipart:
      max-file-size: 4GB
      max-request-size: 4GB
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: demo2
      # username:
      # password:
      auto-index-creation: true

logging:
  level:
    root: info
  file:
    name: /log/demo-mongodb.log
