// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package com.demo.entity.proto;

public final class PersonProto {
    private PersonProto() {
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface PersonOrBuilder extends
            // @@protoc_insertion_point(interface_extends:Person)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string name = 1;</code>
         *
         * @return The name.
         */
        java.lang.String getName();

        /**
         * <code>string name = 1;</code>
         *
         * @return The bytes for name.
         */
        com.google.protobuf.ByteString getNameBytes();

        /**
         * <code>int32 year = 2;</code>
         *
         * @return The year.
         */
        int getYear();

        /**
         * <code>bool gender = 3;</code>
         *
         * @return The gender.
         */
        boolean getGender();

        /**
         * <code>int64 date = 4;</code>
         *
         * @return The date.
         */
        long getDate();

        /**
         * <code>string address = 5;</code>
         *
         * @return The address.
         */
        java.lang.String getAddress();

        /**
         * <code>string address = 5;</code>
         *
         * @return The bytes for address.
         */
        com.google.protobuf.ByteString getAddressBytes();

        /**
         * <pre>
         * 数组
         * </pre>
         *
         * <code>repeated .Car cars = 6;</code>
         */
        java.util.List<com.demo.entity.proto.PersonProto.Car> getCarsList();

        /**
         * <pre>
         * 数组
         * </pre>
         *
         * <code>repeated .Car cars = 6;</code>
         */
        com.demo.entity.proto.PersonProto.Car getCars(int index);

        /**
         * <pre>
         * 数组
         * </pre>
         *
         * <code>repeated .Car cars = 6;</code>
         */
        int getCarsCount();

        /**
         * <pre>
         * 数组
         * </pre>
         *
         * <code>repeated .Car cars = 6;</code>
         */
        java.util.List<? extends com.demo.entity.proto.PersonProto.CarOrBuilder> getCarsOrBuilderList();

        /**
         * <pre>
         * 数组
         * </pre>
         *
         * <code>repeated .Car cars = 6;</code>
         */
        com.demo.entity.proto.PersonProto.CarOrBuilder getCarsOrBuilder(int index);

        /**
         * <pre>
         * Map
         * </pre>
         *
         * <code>map&lt;string, string&gt; other = 7;</code>
         */
        int getOtherCount();

        /**
         * <pre>
         * Map
         * </pre>
         *
         * <code>map&lt;string, string&gt; other = 7;</code>
         */
        boolean containsOther(java.lang.String key);

        /**
         * Use {@link #getOtherMap()} instead.
         */
        @java.lang.Deprecated
        java.util.Map<java.lang.String, java.lang.String> getOther();

        /**
         * <pre>
         * Map
         * </pre>
         *
         * <code>map&lt;string, string&gt; other = 7;</code>
         */
        java.util.Map<java.lang.String, java.lang.String> getOtherMap();

        /**
         * <pre>
         * Map
         * </pre>
         *
         * <code>map&lt;string, string&gt; other = 7;</code>
         */

        java.lang.String getOtherOrDefault(java.lang.String key, java.lang.String defaultValue);

        /**
         * <pre>
         * Map
         * </pre>
         *
         * <code>map&lt;string, string&gt; other = 7;</code>
         */

        java.lang.String getOtherOrThrow(java.lang.String key);
    }

    /**
     * <pre>
     * 内部类Person
     * </pre>
     * <p>
     * Protobuf type {@code Person}
     */
    public static final class Person extends com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:Person)
            PersonOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use Person.newBuilder() to construct.
        private Person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private Person() {
            name_ = "";
            address_ = "";
            cars_ = java.util.Collections.emptyList();
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
            return new Person();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
            return this.unknownFields;
        }

        private Person(com.google.protobuf.CodedInputStream input,
                       com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            java.lang.String s = input.readStringRequireUtf8();

                            name_ = s;
                            break;
                        }
                        case 16: {

                            year_ = input.readInt32();
                            break;
                        }
                        case 24: {

                            gender_ = input.readBool();
                            break;
                        }
                        case 32: {

                            date_ = input.readInt64();
                            break;
                        }
                        case 42: {
                            java.lang.String s = input.readStringRequireUtf8();

                            address_ = s;
                            break;
                        }
                        case 50: {
                            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                                cars_ = new java.util.ArrayList<com.demo.entity.proto.PersonProto.Car>();
                                mutable_bitField0_ |= 0x00000001;
                            }
                            cars_.add(input.readMessage(com.demo.entity.proto.PersonProto.Car.parser(),
                                    extensionRegistry));
                            break;
                        }
                        case 58: {
                            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                                other_ = com.google.protobuf.MapField.newMapField(OtherDefaultEntryHolder.defaultEntry);
                                mutable_bitField0_ |= 0x00000002;
                            }
                            com.google.protobuf.MapEntry<java.lang.String, java.lang.String> other__ =
                                    input.readMessage(OtherDefaultEntryHolder.defaultEntry.getParserForType(),
                                            extensionRegistry);
                            other_.getMutableMap().put(other__.getKey(), other__.getValue());
                            break;
                        }
                        default: {
                            if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000001) != 0)) {
                    cars_ = java.util.Collections.unmodifiableList(cars_);
                }
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return com.demo.entity.proto.PersonProto.internal_static_Person_descriptor;
        }

        @SuppressWarnings({"rawtypes"})
        @java.lang.Override
        protected com.google.protobuf.MapField internalGetMapField(int number) {
            switch (number) {
                case 7:
                    return internalGetOther();
                default:
                    throw new RuntimeException("Invalid map field number: " + number);
            }
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
            return com.demo.entity.proto.PersonProto.internal_static_Person_fieldAccessorTable.ensureFieldAccessorsInitialized(com.demo.entity.proto.PersonProto.Person.class, com.demo.entity.proto.PersonProto.Person.Builder.class);
        }

        public static final int NAME_FIELD_NUMBER = 1;
        private volatile java.lang.Object name_;

        /**
         * <code>string name = 1;</code>
         *
         * @return The name.
         */
        @java.lang.Override
        public java.lang.String getName() {
            java.lang.Object ref = name_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                name_ = s;
                return s;
            }
        }

        /**
         * <code>string name = 1;</code>
         *
         * @return The bytes for name.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getNameBytes() {
            java.lang.Object ref = name_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                name_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int YEAR_FIELD_NUMBER = 2;
        private int year_;

        /**
         * <code>int32 year = 2;</code>
         *
         * @return The year.
         */
        @java.lang.Override
        public int getYear() {
            return year_;
        }

        public static final int GENDER_FIELD_NUMBER = 3;
        private boolean gender_;

        /**
         * <code>bool gender = 3;</code>
         *
         * @return The gender.
         */
        @java.lang.Override
        public boolean getGender() {
            return gender_;
        }

        public static final int DATE_FIELD_NUMBER = 4;
        private long date_;

        /**
         * <code>int64 date = 4;</code>
         *
         * @return The date.
         */
        @java.lang.Override
        public long getDate() {
            return date_;
        }

        public static final int ADDRESS_FIELD_NUMBER = 5;
        private volatile java.lang.Object address_;

        /**
         * <code>string address = 5;</code>
         *
         * @return The address.
         */
        @java.lang.Override
        public java.lang.String getAddress() {
            java.lang.Object ref = address_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                address_ = s;
                return s;
            }
        }

        /**
         * <code>string address = 5;</code>
         *
         * @return The bytes for address.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getAddressBytes() {
            java.lang.Object ref = address_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                address_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int CARS_FIELD_NUMBER = 6;
        private java.util.List<com.demo.entity.proto.PersonProto.Car> cars_;

        /**
         * <pre>
         * 数组
         * </pre>
         *
         * <code>repeated .Car cars = 6;</code>
         */
        @java.lang.Override
        public java.util.List<com.demo.entity.proto.PersonProto.Car> getCarsList() {
            return cars_;
        }

        /**
         * <pre>
         * 数组
         * </pre>
         *
         * <code>repeated .Car cars = 6;</code>
         */
        @java.lang.Override
        public java.util.List<? extends com.demo.entity.proto.PersonProto.CarOrBuilder> getCarsOrBuilderList() {
            return cars_;
        }

        /**
         * <pre>
         * 数组
         * </pre>
         *
         * <code>repeated .Car cars = 6;</code>
         */
        @java.lang.Override
        public int getCarsCount() {
            return cars_.size();
        }

        /**
         * <pre>
         * 数组
         * </pre>
         *
         * <code>repeated .Car cars = 6;</code>
         */
        @java.lang.Override
        public com.demo.entity.proto.PersonProto.Car getCars(int index) {
            return cars_.get(index);
        }

        /**
         * <pre>
         * 数组
         * </pre>
         *
         * <code>repeated .Car cars = 6;</code>
         */
        @java.lang.Override
        public com.demo.entity.proto.PersonProto.CarOrBuilder getCarsOrBuilder(int index) {
            return cars_.get(index);
        }

        public static final int OTHER_FIELD_NUMBER = 7;

        private static final class OtherDefaultEntryHolder {
            static final com.google.protobuf.MapEntry<java.lang.String, java.lang.String> defaultEntry =
                    com.google.protobuf.MapEntry.<java.lang.String, java.lang.String>newDefaultInstance(com.demo.entity.proto.PersonProto.internal_static_Person_OtherEntry_descriptor, com.google.protobuf.WireFormat.FieldType.STRING, "", com.google.protobuf.WireFormat.FieldType.STRING, "");
        }

        private com.google.protobuf.MapField<java.lang.String, java.lang.String> other_;

        private com.google.protobuf.MapField<java.lang.String, java.lang.String> internalGetOther() {
            if (other_ == null) {
                return com.google.protobuf.MapField.emptyMapField(OtherDefaultEntryHolder.defaultEntry);
            }
            return other_;
        }

        public int getOtherCount() {
            return internalGetOther().getMap().size();
        }

        /**
         * <pre>
         * Map
         * </pre>
         *
         * <code>map&lt;string, string&gt; other = 7;</code>
         */

        @java.lang.Override
        public boolean containsOther(java.lang.String key) {
            if (key == null) {
                throw new NullPointerException("map key");
            }
            return internalGetOther().getMap().containsKey(key);
        }

        /**
         * Use {@link #getOtherMap()} instead.
         */
        @java.lang.Override
        @java.lang.Deprecated
        public java.util.Map<java.lang.String, java.lang.String> getOther() {
            return getOtherMap();
        }

        /**
         * <pre>
         * Map
         * </pre>
         *
         * <code>map&lt;string, string&gt; other = 7;</code>
         */
        @java.lang.Override

        public java.util.Map<java.lang.String, java.lang.String> getOtherMap() {
            return internalGetOther().getMap();
        }

        /**
         * <pre>
         * Map
         * </pre>
         *
         * <code>map&lt;string, string&gt; other = 7;</code>
         */
        @java.lang.Override

        public java.lang.String getOtherOrDefault(java.lang.String key, java.lang.String defaultValue) {
            if (key == null) {
                throw new NullPointerException("map key");
            }
            java.util.Map<java.lang.String, java.lang.String> map = internalGetOther().getMap();
            return map.containsKey(key) ? map.get(key) : defaultValue;
        }

        /**
         * <pre>
         * Map
         * </pre>
         *
         * <code>map&lt;string, string&gt; other = 7;</code>
         */
        @java.lang.Override

        public java.lang.String getOtherOrThrow(java.lang.String key) {
            if (key == null) {
                throw new NullPointerException("map key");
            }
            java.util.Map<java.lang.String, java.lang.String> map = internalGetOther().getMap();
            if (!map.containsKey(key)) {
                throw new java.lang.IllegalArgumentException();
            }
            return map.get(key);
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1)
                return true;
            if (isInitialized == 0)
                return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
            }
            if (year_ != 0) {
                output.writeInt32(2, year_);
            }
            if (gender_ != false) {
                output.writeBool(3, gender_);
            }
            if (date_ != 0L) {
                output.writeInt64(4, date_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(address_)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 5, address_);
            }
            for (int i = 0; i < cars_.size(); i++) {
                output.writeMessage(6, cars_.get(i));
            }
            com.google.protobuf.GeneratedMessageV3.serializeStringMapTo(output, internalGetOther(),
                    OtherDefaultEntryHolder.defaultEntry, 7);
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1)
                return size;

            size = 0;
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
            }
            if (year_ != 0) {
                size += com.google.protobuf.CodedOutputStream.computeInt32Size(2, year_);
            }
            if (gender_ != false) {
                size += com.google.protobuf.CodedOutputStream.computeBoolSize(3, gender_);
            }
            if (date_ != 0L) {
                size += com.google.protobuf.CodedOutputStream.computeInt64Size(4, date_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(address_)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, address_);
            }
            for (int i = 0; i < cars_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream.computeMessageSize(6, cars_.get(i));
            }
            for (java.util.Map.Entry<java.lang.String, java.lang.String> entry :
                    internalGetOther().getMap().entrySet()) {
                com.google.protobuf.MapEntry<java.lang.String, java.lang.String> other__ =
                        OtherDefaultEntryHolder.defaultEntry.newBuilderForType().setKey(entry.getKey()).setValue(entry.getValue()).build();
                size += com.google.protobuf.CodedOutputStream.computeMessageSize(7, other__);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.demo.entity.proto.PersonProto.Person)) {
                return super.equals(obj);
            }
            com.demo.entity.proto.PersonProto.Person other = (com.demo.entity.proto.PersonProto.Person) obj;

            if (!getName().equals(other.getName()))
                return false;
            if (getYear() != other.getYear())
                return false;
            if (getGender() != other.getGender())
                return false;
            if (getDate() != other.getDate())
                return false;
            if (!getAddress().equals(other.getAddress()))
                return false;
            if (!getCarsList().equals(other.getCarsList()))
                return false;
            if (!internalGetOther().equals(other.internalGetOther()))
                return false;
            if (!unknownFields.equals(other.unknownFields))
                return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + NAME_FIELD_NUMBER;
            hash = (53 * hash) + getName().hashCode();
            hash = (37 * hash) + YEAR_FIELD_NUMBER;
            hash = (53 * hash) + getYear();
            hash = (37 * hash) + GENDER_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(getGender());
            hash = (37 * hash) + DATE_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getDate());
            hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
            hash = (53 * hash) + getAddress().hashCode();
            if (getCarsCount() > 0) {
                hash = (37 * hash) + CARS_FIELD_NUMBER;
                hash = (53 * hash) + getCarsList().hashCode();
            }
            if (!internalGetOther().getMap().isEmpty()) {
                hash = (37 * hash) + OTHER_FIELD_NUMBER;
                hash = (53 * hash) + internalGetOther().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.demo.entity.proto.PersonProto.Person parseFrom(java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.demo.entity.proto.PersonProto.Person parseFrom(java.nio.ByteBuffer data,
                                                                         com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.demo.entity.proto.PersonProto.Person parseFrom(com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.demo.entity.proto.PersonProto.Person parseFrom(com.google.protobuf.ByteString data,
                                                                         com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.demo.entity.proto.PersonProto.Person parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.demo.entity.proto.PersonProto.Person parseFrom(byte[] data,
                                                                         com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.demo.entity.proto.PersonProto.Person parseFrom(java.io.InputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }

        public static com.demo.entity.proto.PersonProto.Person parseFrom(java.io.InputStream input,
                                                                         com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.demo.entity.proto.PersonProto.Person parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
        }

        public static com.demo.entity.proto.PersonProto.Person parseDelimitedFrom(java.io.InputStream input,
                                                                                  com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input,
                    extensionRegistry);
        }

        public static com.demo.entity.proto.PersonProto.Person parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }

        public static com.demo.entity.proto.PersonProto.Person parseFrom(com.google.protobuf.CodedInputStream input,
                                                                         com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(com.demo.entity.proto.PersonProto.Person prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * <pre>
         * 内部类Person
         * </pre>
         * <p>
         * Protobuf type {@code Person}
         */
        public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:Person)
                com.demo.entity.proto.PersonProto.PersonOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return com.demo.entity.proto.PersonProto.internal_static_Person_descriptor;
            }

            @SuppressWarnings({"rawtypes"})
            protected com.google.protobuf.MapField internalGetMapField(int number) {
                switch (number) {
                    case 7:
                        return internalGetOther();
                    default:
                        throw new RuntimeException("Invalid map field number: " + number);
                }
            }

            @SuppressWarnings({"rawtypes"})
            protected com.google.protobuf.MapField internalGetMutableMapField(int number) {
                switch (number) {
                    case 7:
                        return internalGetMutableOther();
                    default:
                        throw new RuntimeException("Invalid map field number: " + number);
                }
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
                return com.demo.entity.proto.PersonProto.internal_static_Person_fieldAccessorTable.ensureFieldAccessorsInitialized(com.demo.entity.proto.PersonProto.Person.class, com.demo.entity.proto.PersonProto.Person.Builder.class);
            }

            // Construct using com.demo.entity.proto.PersonProto.Person.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
                    getCarsFieldBuilder();
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                name_ = "";

                year_ = 0;

                gender_ = false;

                date_ = 0L;

                address_ = "";

                if (carsBuilder_ == null) {
                    cars_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000001);
                } else {
                    carsBuilder_.clear();
                }
                internalGetMutableOther().clear();
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return com.demo.entity.proto.PersonProto.internal_static_Person_descriptor;
            }

            @java.lang.Override
            public com.demo.entity.proto.PersonProto.Person getDefaultInstanceForType() {
                return com.demo.entity.proto.PersonProto.Person.getDefaultInstance();
            }

            @java.lang.Override
            public com.demo.entity.proto.PersonProto.Person build() {
                com.demo.entity.proto.PersonProto.Person result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public com.demo.entity.proto.PersonProto.Person buildPartial() {
                com.demo.entity.proto.PersonProto.Person result = new com.demo.entity.proto.PersonProto.Person(this);
                int from_bitField0_ = bitField0_;
                result.name_ = name_;
                result.year_ = year_;
                result.gender_ = gender_;
                result.date_ = date_;
                result.address_ = address_;
                if (carsBuilder_ == null) {
                    if (((bitField0_ & 0x00000001) != 0)) {
                        cars_ = java.util.Collections.unmodifiableList(cars_);
                        bitField0_ = (bitField0_ & ~0x00000001);
                    }
                    result.cars_ = cars_;
                } else {
                    result.cars_ = carsBuilder_.build();
                }
                result.other_ = internalGetOther();
                result.other_.makeImmutable();
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index,
                                            java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
                                            java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.demo.entity.proto.PersonProto.Person) {
                    return mergeFrom((com.demo.entity.proto.PersonProto.Person) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.demo.entity.proto.PersonProto.Person other) {
                if (other == com.demo.entity.proto.PersonProto.Person.getDefaultInstance())
                    return this;
                if (!other.getName().isEmpty()) {
                    name_ = other.name_;
                    onChanged();
                }
                if (other.getYear() != 0) {
                    setYear(other.getYear());
                }
                if (other.getGender() != false) {
                    setGender(other.getGender());
                }
                if (other.getDate() != 0L) {
                    setDate(other.getDate());
                }
                if (!other.getAddress().isEmpty()) {
                    address_ = other.address_;
                    onChanged();
                }
                if (carsBuilder_ == null) {
                    if (!other.cars_.isEmpty()) {
                        if (cars_.isEmpty()) {
                            cars_ = other.cars_;
                            bitField0_ = (bitField0_ & ~0x00000001);
                        } else {
                            ensureCarsIsMutable();
                            cars_.addAll(other.cars_);
                        }
                        onChanged();
                    }
                } else {
                    if (!other.cars_.isEmpty()) {
                        if (carsBuilder_.isEmpty()) {
                            carsBuilder_.dispose();
                            carsBuilder_ = null;
                            cars_ = other.cars_;
                            bitField0_ = (bitField0_ & ~0x00000001);
                            carsBuilder_ = com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                                    getCarsFieldBuilder() : null;
                        } else {
                            carsBuilder_.addAllMessages(other.cars_);
                        }
                    }
                }
                internalGetMutableOther().mergeFrom(other.internalGetOther());
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                                     com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
                com.demo.entity.proto.PersonProto.Person parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.demo.entity.proto.PersonProto.Person) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private java.lang.Object name_ = "";

            /**
             * <code>string name = 1;</code>
             *
             * @return The name.
             */
            public java.lang.String getName() {
                java.lang.Object ref = name_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    name_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string name = 1;</code>
             *
             * @return The bytes for name.
             */
            public com.google.protobuf.ByteString getNameBytes() {
                java.lang.Object ref = name_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                    name_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string name = 1;</code>
             *
             * @param value The name to set.
             * @return This builder for chaining.
             */
            public Builder setName(java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                name_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string name = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearName() {

                name_ = getDefaultInstance().getName();
                onChanged();
                return this;
            }

            /**
             * <code>string name = 1;</code>
             *
             * @param value The bytes for name to set.
             * @return This builder for chaining.
             */
            public Builder setNameBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                name_ = value;
                onChanged();
                return this;
            }

            private int year_;

            /**
             * <code>int32 year = 2;</code>
             *
             * @return The year.
             */
            @java.lang.Override
            public int getYear() {
                return year_;
            }

            /**
             * <code>int32 year = 2;</code>
             *
             * @param value The year to set.
             * @return This builder for chaining.
             */
            public Builder setYear(int value) {

                year_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int32 year = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearYear() {

                year_ = 0;
                onChanged();
                return this;
            }

            private boolean gender_;

            /**
             * <code>bool gender = 3;</code>
             *
             * @return The gender.
             */
            @java.lang.Override
            public boolean getGender() {
                return gender_;
            }

            /**
             * <code>bool gender = 3;</code>
             *
             * @param value The gender to set.
             * @return This builder for chaining.
             */
            public Builder setGender(boolean value) {

                gender_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>bool gender = 3;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearGender() {

                gender_ = false;
                onChanged();
                return this;
            }

            private long date_;

            /**
             * <code>int64 date = 4;</code>
             *
             * @return The date.
             */
            @java.lang.Override
            public long getDate() {
                return date_;
            }

            /**
             * <code>int64 date = 4;</code>
             *
             * @param value The date to set.
             * @return This builder for chaining.
             */
            public Builder setDate(long value) {

                date_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int64 date = 4;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearDate() {

                date_ = 0L;
                onChanged();
                return this;
            }

            private java.lang.Object address_ = "";

            /**
             * <code>string address = 5;</code>
             *
             * @return The address.
             */
            public java.lang.String getAddress() {
                java.lang.Object ref = address_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    address_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string address = 5;</code>
             *
             * @return The bytes for address.
             */
            public com.google.protobuf.ByteString getAddressBytes() {
                java.lang.Object ref = address_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                    address_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string address = 5;</code>
             *
             * @param value The address to set.
             * @return This builder for chaining.
             */
            public Builder setAddress(java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                address_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string address = 5;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearAddress() {

                address_ = getDefaultInstance().getAddress();
                onChanged();
                return this;
            }

            /**
             * <code>string address = 5;</code>
             *
             * @param value The bytes for address to set.
             * @return This builder for chaining.
             */
            public Builder setAddressBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                address_ = value;
                onChanged();
                return this;
            }

            private java.util.List<com.demo.entity.proto.PersonProto.Car> cars_ = java.util.Collections.emptyList();

            private void ensureCarsIsMutable() {
                if (!((bitField0_ & 0x00000001) != 0)) {
                    cars_ = new java.util.ArrayList<com.demo.entity.proto.PersonProto.Car>(cars_);
                    bitField0_ |= 0x00000001;
                }
            }

            private com.google.protobuf.RepeatedFieldBuilderV3<com.demo.entity.proto.PersonProto.Car,
                    com.demo.entity.proto.PersonProto.Car.Builder, com.demo.entity.proto.PersonProto.CarOrBuilder> carsBuilder_;

            /**
             * <pre>
             * 数组
             * </pre>
             *
             * <code>repeated .Car cars = 6;</code>
             */
            public java.util.List<com.demo.entity.proto.PersonProto.Car> getCarsList() {
                if (carsBuilder_ == null) {
                    return java.util.Collections.unmodifiableList(cars_);
                } else {
                    return carsBuilder_.getMessageList();
                }
            }

            /**
             * <pre>
             * 数组
             * </pre>
             *
             * <code>repeated .Car cars = 6;</code>
             */
            public int getCarsCount() {
                if (carsBuilder_ == null) {
                    return cars_.size();
                } else {
                    return carsBuilder_.getCount();
                }
            }

            /**
             * <pre>
             * 数组
             * </pre>
             *
             * <code>repeated .Car cars = 6;</code>
             */
            public com.demo.entity.proto.PersonProto.Car getCars(int index) {
                if (carsBuilder_ == null) {
                    return cars_.get(index);
                } else {
                    return carsBuilder_.getMessage(index);
                }
            }

            /**
             * <pre>
             * 数组
             * </pre>
             *
             * <code>repeated .Car cars = 6;</code>
             */
            public Builder setCars(int index, com.demo.entity.proto.PersonProto.Car value) {
                if (carsBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureCarsIsMutable();
                    cars_.set(index, value);
                    onChanged();
                } else {
                    carsBuilder_.setMessage(index, value);
                }
                return this;
            }

            /**
             * <pre>
             * 数组
             * </pre>
             *
             * <code>repeated .Car cars = 6;</code>
             */
            public Builder setCars(int index, com.demo.entity.proto.PersonProto.Car.Builder builderForValue) {
                if (carsBuilder_ == null) {
                    ensureCarsIsMutable();
                    cars_.set(index, builderForValue.build());
                    onChanged();
                } else {
                    carsBuilder_.setMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <pre>
             * 数组
             * </pre>
             *
             * <code>repeated .Car cars = 6;</code>
             */
            public Builder addCars(com.demo.entity.proto.PersonProto.Car value) {
                if (carsBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureCarsIsMutable();
                    cars_.add(value);
                    onChanged();
                } else {
                    carsBuilder_.addMessage(value);
                }
                return this;
            }

            /**
             * <pre>
             * 数组
             * </pre>
             *
             * <code>repeated .Car cars = 6;</code>
             */
            public Builder addCars(int index, com.demo.entity.proto.PersonProto.Car value) {
                if (carsBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureCarsIsMutable();
                    cars_.add(index, value);
                    onChanged();
                } else {
                    carsBuilder_.addMessage(index, value);
                }
                return this;
            }

            /**
             * <pre>
             * 数组
             * </pre>
             *
             * <code>repeated .Car cars = 6;</code>
             */
            public Builder addCars(com.demo.entity.proto.PersonProto.Car.Builder builderForValue) {
                if (carsBuilder_ == null) {
                    ensureCarsIsMutable();
                    cars_.add(builderForValue.build());
                    onChanged();
                } else {
                    carsBuilder_.addMessage(builderForValue.build());
                }
                return this;
            }

            /**
             * <pre>
             * 数组
             * </pre>
             *
             * <code>repeated .Car cars = 6;</code>
             */
            public Builder addCars(int index, com.demo.entity.proto.PersonProto.Car.Builder builderForValue) {
                if (carsBuilder_ == null) {
                    ensureCarsIsMutable();
                    cars_.add(index, builderForValue.build());
                    onChanged();
                } else {
                    carsBuilder_.addMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <pre>
             * 数组
             * </pre>
             *
             * <code>repeated .Car cars = 6;</code>
             */
            public Builder addAllCars(java.lang.Iterable<? extends com.demo.entity.proto.PersonProto.Car> values) {
                if (carsBuilder_ == null) {
                    ensureCarsIsMutable();
                    com.google.protobuf.AbstractMessageLite.Builder.addAll(values, cars_);
                    onChanged();
                } else {
                    carsBuilder_.addAllMessages(values);
                }
                return this;
            }

            /**
             * <pre>
             * 数组
             * </pre>
             *
             * <code>repeated .Car cars = 6;</code>
             */
            public Builder clearCars() {
                if (carsBuilder_ == null) {
                    cars_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000001);
                    onChanged();
                } else {
                    carsBuilder_.clear();
                }
                return this;
            }

            /**
             * <pre>
             * 数组
             * </pre>
             *
             * <code>repeated .Car cars = 6;</code>
             */
            public Builder removeCars(int index) {
                if (carsBuilder_ == null) {
                    ensureCarsIsMutable();
                    cars_.remove(index);
                    onChanged();
                } else {
                    carsBuilder_.remove(index);
                }
                return this;
            }

            /**
             * <pre>
             * 数组
             * </pre>
             *
             * <code>repeated .Car cars = 6;</code>
             */
            public com.demo.entity.proto.PersonProto.Car.Builder getCarsBuilder(int index) {
                return getCarsFieldBuilder().getBuilder(index);
            }

            /**
             * <pre>
             * 数组
             * </pre>
             *
             * <code>repeated .Car cars = 6;</code>
             */
            public com.demo.entity.proto.PersonProto.CarOrBuilder getCarsOrBuilder(int index) {
                if (carsBuilder_ == null) {
                    return cars_.get(index);
                } else {
                    return carsBuilder_.getMessageOrBuilder(index);
                }
            }

            /**
             * <pre>
             * 数组
             * </pre>
             *
             * <code>repeated .Car cars = 6;</code>
             */
            public java.util.List<? extends com.demo.entity.proto.PersonProto.CarOrBuilder> getCarsOrBuilderList() {
                if (carsBuilder_ != null) {
                    return carsBuilder_.getMessageOrBuilderList();
                } else {
                    return java.util.Collections.unmodifiableList(cars_);
                }
            }

            /**
             * <pre>
             * 数组
             * </pre>
             *
             * <code>repeated .Car cars = 6;</code>
             */
            public com.demo.entity.proto.PersonProto.Car.Builder addCarsBuilder() {
                return getCarsFieldBuilder().addBuilder(com.demo.entity.proto.PersonProto.Car.getDefaultInstance());
            }

            /**
             * <pre>
             * 数组
             * </pre>
             *
             * <code>repeated .Car cars = 6;</code>
             */
            public com.demo.entity.proto.PersonProto.Car.Builder addCarsBuilder(int index) {
                return getCarsFieldBuilder().addBuilder(index,
                        com.demo.entity.proto.PersonProto.Car.getDefaultInstance());
            }

            /**
             * <pre>
             * 数组
             * </pre>
             *
             * <code>repeated .Car cars = 6;</code>
             */
            public java.util.List<com.demo.entity.proto.PersonProto.Car.Builder> getCarsBuilderList() {
                return getCarsFieldBuilder().getBuilderList();
            }

            private com.google.protobuf.RepeatedFieldBuilderV3<com.demo.entity.proto.PersonProto.Car,
                    com.demo.entity.proto.PersonProto.Car.Builder, com.demo.entity.proto.PersonProto.CarOrBuilder> getCarsFieldBuilder() {
                if (carsBuilder_ == null) {
                    carsBuilder_ =
                            new com.google.protobuf.RepeatedFieldBuilderV3<com.demo.entity.proto.PersonProto.Car,
                                    com.demo.entity.proto.PersonProto.Car.Builder,
                                    com.demo.entity.proto.PersonProto.CarOrBuilder>(cars_,
                                    ((bitField0_ & 0x00000001) != 0), getParentForChildren(), isClean());
                    cars_ = null;
                }
                return carsBuilder_;
            }

            private com.google.protobuf.MapField<java.lang.String, java.lang.String> other_;

            private com.google.protobuf.MapField<java.lang.String, java.lang.String> internalGetOther() {
                if (other_ == null) {
                    return com.google.protobuf.MapField.emptyMapField(OtherDefaultEntryHolder.defaultEntry);
                }
                return other_;
            }

            private com.google.protobuf.MapField<java.lang.String, java.lang.String> internalGetMutableOther() {
                onChanged();
                ;
                if (other_ == null) {
                    other_ = com.google.protobuf.MapField.newMapField(OtherDefaultEntryHolder.defaultEntry);
                }
                if (!other_.isMutable()) {
                    other_ = other_.copy();
                }
                return other_;
            }

            public int getOtherCount() {
                return internalGetOther().getMap().size();
            }

            /**
             * <pre>
             * Map
             * </pre>
             *
             * <code>map&lt;string, string&gt; other = 7;</code>
             */

            @java.lang.Override
            public boolean containsOther(java.lang.String key) {
                if (key == null) {
                    throw new NullPointerException("map key");
                }
                return internalGetOther().getMap().containsKey(key);
            }

            /**
             * Use {@link #getOtherMap()} instead.
             */
            @java.lang.Override
            @java.lang.Deprecated
            public java.util.Map<java.lang.String, java.lang.String> getOther() {
                return getOtherMap();
            }

            /**
             * <pre>
             * Map
             * </pre>
             *
             * <code>map&lt;string, string&gt; other = 7;</code>
             */
            @java.lang.Override

            public java.util.Map<java.lang.String, java.lang.String> getOtherMap() {
                return internalGetOther().getMap();
            }

            /**
             * <pre>
             * Map
             * </pre>
             *
             * <code>map&lt;string, string&gt; other = 7;</code>
             */
            @java.lang.Override

            public java.lang.String getOtherOrDefault(java.lang.String key, java.lang.String defaultValue) {
                if (key == null) {
                    throw new NullPointerException("map key");
                }
                java.util.Map<java.lang.String, java.lang.String> map = internalGetOther().getMap();
                return map.containsKey(key) ? map.get(key) : defaultValue;
            }

            /**
             * <pre>
             * Map
             * </pre>
             *
             * <code>map&lt;string, string&gt; other = 7;</code>
             */
            @java.lang.Override

            public java.lang.String getOtherOrThrow(java.lang.String key) {
                if (key == null) {
                    throw new NullPointerException("map key");
                }
                java.util.Map<java.lang.String, java.lang.String> map = internalGetOther().getMap();
                if (!map.containsKey(key)) {
                    throw new java.lang.IllegalArgumentException();
                }
                return map.get(key);
            }

            public Builder clearOther() {
                internalGetMutableOther().getMutableMap().clear();
                return this;
            }

            /**
             * <pre>
             * Map
             * </pre>
             *
             * <code>map&lt;string, string&gt; other = 7;</code>
             */

            public Builder removeOther(java.lang.String key) {
                if (key == null) {
                    throw new NullPointerException("map key");
                }
                internalGetMutableOther().getMutableMap().remove(key);
                return this;
            }

            /**
             * Use alternate mutation accessors instead.
             */
            @java.lang.Deprecated
            public java.util.Map<java.lang.String, java.lang.String> getMutableOther() {
                return internalGetMutableOther().getMutableMap();
            }

            /**
             * <pre>
             * Map
             * </pre>
             *
             * <code>map&lt;string, string&gt; other = 7;</code>
             */
            public Builder putOther(java.lang.String key, java.lang.String value) {
                if (key == null) {
                    throw new NullPointerException("map key");
                }
                if (value == null) {
                    throw new NullPointerException("map value");
                }

                internalGetMutableOther().getMutableMap().put(key, value);
                return this;
            }

            /**
             * <pre>
             * Map
             * </pre>
             *
             * <code>map&lt;string, string&gt; other = 7;</code>
             */

            public Builder putAllOther(java.util.Map<java.lang.String, java.lang.String> values) {
                internalGetMutableOther().getMutableMap().putAll(values);
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:Person)
        }

        // @@protoc_insertion_point(class_scope:Person)
        private static final com.demo.entity.proto.PersonProto.Person DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new com.demo.entity.proto.PersonProto.Person();
        }

        public static com.demo.entity.proto.PersonProto.Person getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Person> PARSER =
                new com.google.protobuf.AbstractParser<Person>() {
            @java.lang.Override
            public Person parsePartialFrom(com.google.protobuf.CodedInputStream input,
                                           com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
                return new Person(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Person> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Person> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public com.demo.entity.proto.PersonProto.Person getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface CarOrBuilder extends
            // @@protoc_insertion_point(interface_extends:Car)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string name = 1;</code>
         *
         * @return The name.
         */
        java.lang.String getName();

        /**
         * <code>string name = 1;</code>
         *
         * @return The bytes for name.
         */
        com.google.protobuf.ByteString getNameBytes();

        /**
         * <code>string color = 2;</code>
         *
         * @return The color.
         */
        java.lang.String getColor();

        /**
         * <code>string color = 2;</code>
         *
         * @return The bytes for color.
         */
        com.google.protobuf.ByteString getColorBytes();
    }

    /**
     * <pre>
     * 内部类Car
     * </pre>
     * <p>
     * Protobuf type {@code Car}
     */
    public static final class Car extends com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:Car)
            CarOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use Car.newBuilder() to construct.
        private Car(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private Car() {
            name_ = "";
            color_ = "";
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
            return new Car();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
            return this.unknownFields;
        }

        private Car(com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            java.lang.String s = input.readStringRequireUtf8();

                            name_ = s;
                            break;
                        }
                        case 18: {
                            java.lang.String s = input.readStringRequireUtf8();

                            color_ = s;
                            break;
                        }
                        default: {
                            if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return com.demo.entity.proto.PersonProto.internal_static_Car_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
            return com.demo.entity.proto.PersonProto.internal_static_Car_fieldAccessorTable.ensureFieldAccessorsInitialized(com.demo.entity.proto.PersonProto.Car.class, com.demo.entity.proto.PersonProto.Car.Builder.class);
        }

        public static final int NAME_FIELD_NUMBER = 1;
        private volatile java.lang.Object name_;

        /**
         * <code>string name = 1;</code>
         *
         * @return The name.
         */
        @java.lang.Override
        public java.lang.String getName() {
            java.lang.Object ref = name_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                name_ = s;
                return s;
            }
        }

        /**
         * <code>string name = 1;</code>
         *
         * @return The bytes for name.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getNameBytes() {
            java.lang.Object ref = name_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                name_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int COLOR_FIELD_NUMBER = 2;
        private volatile java.lang.Object color_;

        /**
         * <code>string color = 2;</code>
         *
         * @return The color.
         */
        @java.lang.Override
        public java.lang.String getColor() {
            java.lang.Object ref = color_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                color_ = s;
                return s;
            }
        }

        /**
         * <code>string color = 2;</code>
         *
         * @return The bytes for color.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getColorBytes() {
            java.lang.Object ref = color_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                color_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1)
                return true;
            if (isInitialized == 0)
                return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(color_)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, color_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1)
                return size;

            size = 0;
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(color_)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, color_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.demo.entity.proto.PersonProto.Car)) {
                return super.equals(obj);
            }
            com.demo.entity.proto.PersonProto.Car other = (com.demo.entity.proto.PersonProto.Car) obj;

            if (!getName().equals(other.getName()))
                return false;
            if (!getColor().equals(other.getColor()))
                return false;
            if (!unknownFields.equals(other.unknownFields))
                return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + NAME_FIELD_NUMBER;
            hash = (53 * hash) + getName().hashCode();
            hash = (37 * hash) + COLOR_FIELD_NUMBER;
            hash = (53 * hash) + getColor().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.demo.entity.proto.PersonProto.Car parseFrom(java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.demo.entity.proto.PersonProto.Car parseFrom(java.nio.ByteBuffer data,
                                                                      com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.demo.entity.proto.PersonProto.Car parseFrom(com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.demo.entity.proto.PersonProto.Car parseFrom(com.google.protobuf.ByteString data,
                                                                      com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.demo.entity.proto.PersonProto.Car parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.demo.entity.proto.PersonProto.Car parseFrom(byte[] data,
                                                                      com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.demo.entity.proto.PersonProto.Car parseFrom(java.io.InputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }

        public static com.demo.entity.proto.PersonProto.Car parseFrom(java.io.InputStream input,
                                                                      com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.demo.entity.proto.PersonProto.Car parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
        }

        public static com.demo.entity.proto.PersonProto.Car parseDelimitedFrom(java.io.InputStream input,
                                                                               com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input,
                    extensionRegistry);
        }

        public static com.demo.entity.proto.PersonProto.Car parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }

        public static com.demo.entity.proto.PersonProto.Car parseFrom(com.google.protobuf.CodedInputStream input,
                                                                      com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(com.demo.entity.proto.PersonProto.Car prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * <pre>
         * 内部类Car
         * </pre>
         * <p>
         * Protobuf type {@code Car}
         */
        public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:Car)
                com.demo.entity.proto.PersonProto.CarOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return com.demo.entity.proto.PersonProto.internal_static_Car_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
                return com.demo.entity.proto.PersonProto.internal_static_Car_fieldAccessorTable.ensureFieldAccessorsInitialized(com.demo.entity.proto.PersonProto.Car.class, com.demo.entity.proto.PersonProto.Car.Builder.class);
            }

            // Construct using com.demo.entity.proto.PersonProto.Car.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                name_ = "";

                color_ = "";

                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return com.demo.entity.proto.PersonProto.internal_static_Car_descriptor;
            }

            @java.lang.Override
            public com.demo.entity.proto.PersonProto.Car getDefaultInstanceForType() {
                return com.demo.entity.proto.PersonProto.Car.getDefaultInstance();
            }

            @java.lang.Override
            public com.demo.entity.proto.PersonProto.Car build() {
                com.demo.entity.proto.PersonProto.Car result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public com.demo.entity.proto.PersonProto.Car buildPartial() {
                com.demo.entity.proto.PersonProto.Car result = new com.demo.entity.proto.PersonProto.Car(this);
                result.name_ = name_;
                result.color_ = color_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index,
                                            java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
                                            java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.demo.entity.proto.PersonProto.Car) {
                    return mergeFrom((com.demo.entity.proto.PersonProto.Car) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.demo.entity.proto.PersonProto.Car other) {
                if (other == com.demo.entity.proto.PersonProto.Car.getDefaultInstance())
                    return this;
                if (!other.getName().isEmpty()) {
                    name_ = other.name_;
                    onChanged();
                }
                if (!other.getColor().isEmpty()) {
                    color_ = other.color_;
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
                com.demo.entity.proto.PersonProto.Car parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.demo.entity.proto.PersonProto.Car) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private java.lang.Object name_ = "";

            /**
             * <code>string name = 1;</code>
             *
             * @return The name.
             */
            public java.lang.String getName() {
                java.lang.Object ref = name_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    name_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string name = 1;</code>
             *
             * @return The bytes for name.
             */
            public com.google.protobuf.ByteString getNameBytes() {
                java.lang.Object ref = name_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                    name_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string name = 1;</code>
             *
             * @param value The name to set.
             * @return This builder for chaining.
             */
            public Builder setName(java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                name_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string name = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearName() {

                name_ = getDefaultInstance().getName();
                onChanged();
                return this;
            }

            /**
             * <code>string name = 1;</code>
             *
             * @param value The bytes for name to set.
             * @return This builder for chaining.
             */
            public Builder setNameBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                name_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object color_ = "";

            /**
             * <code>string color = 2;</code>
             *
             * @return The color.
             */
            public java.lang.String getColor() {
                java.lang.Object ref = color_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    color_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string color = 2;</code>
             *
             * @return The bytes for color.
             */
            public com.google.protobuf.ByteString getColorBytes() {
                java.lang.Object ref = color_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                    color_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string color = 2;</code>
             *
             * @param value The color to set.
             * @return This builder for chaining.
             */
            public Builder setColor(java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                color_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string color = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearColor() {

                color_ = getDefaultInstance().getColor();
                onChanged();
                return this;
            }

            /**
             * <code>string color = 2;</code>
             *
             * @param value The bytes for color to set.
             * @return This builder for chaining.
             */
            public Builder setColorBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                color_ = value;
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:Car)
        }

        // @@protoc_insertion_point(class_scope:Car)
        private static final com.demo.entity.proto.PersonProto.Car DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new com.demo.entity.proto.PersonProto.Car();
        }

        public static com.demo.entity.proto.PersonProto.Car getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Car> PARSER = new com.google.protobuf.AbstractParser<Car>() {
            @java.lang.Override
            public Car parsePartialFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
                return new Car(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Car> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Car> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public com.demo.entity.proto.PersonProto.Car getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor internal_static_Person_descriptor;
    private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_Person_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor internal_static_Person_OtherEntry_descriptor;
    private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_Person_OtherEntry_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor internal_static_Car_descriptor;
    private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_Car_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

    static {
        java.lang.String[] descriptorData = {"\n\014person.proto\"\270\001\n\006Person\022\014\n\004name\030\001 \001(\t\022" + "\014\n\004year\030\002 \001(\005\022\016\n\006gender\030\003 \001(\010\022\014\n\004date\030\004 " + "\001(\003\022\017\n\007address\030\005 \001(\t\022\022\n\004cars\030\006 \003(\0132\004.Car" + "\022!\n\005other\030\007 \003(\0132\022.Person.OtherEntry\032,\n\nO" + "therEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028" + "\001\"\"\n\003Car\022\014\n\004name\030\001 \001(\t\022\r\n\005color\030\002 \001(\tB$\n" + "\025com.demo.entity.protoB\013PersonProtob\006pro" + "to3"};
        descriptor = com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData, new com.google.protobuf.Descriptors.FileDescriptor[]{});
        internal_static_Person_descriptor = getDescriptor().getMessageTypes().get(0);
        internal_static_Person_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(internal_static_Person_descriptor, new java.lang.String[]{"Name", "Year", "Gender", "Date", "Address", "Cars", "Other",});
        internal_static_Person_OtherEntry_descriptor = internal_static_Person_descriptor.getNestedTypes().get(0);
        internal_static_Person_OtherEntry_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(internal_static_Person_OtherEntry_descriptor, new java.lang.String[]{"Key", "Value",});
        internal_static_Car_descriptor = getDescriptor().getMessageTypes().get(1);
        internal_static_Car_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(internal_static_Car_descriptor, new java.lang.String[]{"Name", "Color",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
