// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: person.proto
// Protobuf Java Version: 4.28.0

package com.demo.entity.proto;

public final class PersonProto {
  private PersonProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 0,
      /* suffix= */ "",
      PersonProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PersonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Person)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 year = 2;</code>
     * @return The year.
     */
    int getYear();

    /**
     * <code>bool gender = 3;</code>
     * @return The gender.
     */
    boolean getGender();

    /**
     * <code>int64 date = 4;</code>
     * @return The date.
     */
    long getDate();

    /**
     * <code>string address = 5;</code>
     * @return The address.
     */
    java.lang.String getAddress();
    /**
     * <code>string address = 5;</code>
     * @return The bytes for address.
     */
    com.google.protobuf.ByteString
        getAddressBytes();

    /**
     * <pre>
     * 数组
     * </pre>
     *
     * <code>repeated .Car cars = 6;</code>
     */
    java.util.List<com.demo.entity.proto.PersonProto.Car> 
        getCarsList();
    /**
     * <pre>
     * 数组
     * </pre>
     *
     * <code>repeated .Car cars = 6;</code>
     */
    com.demo.entity.proto.PersonProto.Car getCars(int index);
    /**
     * <pre>
     * 数组
     * </pre>
     *
     * <code>repeated .Car cars = 6;</code>
     */
    int getCarsCount();
    /**
     * <pre>
     * 数组
     * </pre>
     *
     * <code>repeated .Car cars = 6;</code>
     */
    java.util.List<? extends com.demo.entity.proto.PersonProto.CarOrBuilder> 
        getCarsOrBuilderList();
    /**
     * <pre>
     * 数组
     * </pre>
     *
     * <code>repeated .Car cars = 6;</code>
     */
    com.demo.entity.proto.PersonProto.CarOrBuilder getCarsOrBuilder(
        int index);

    /**
     * <pre>
     * Map
     * </pre>
     *
     * <code>map&lt;string, string&gt; other = 7;</code>
     */
    int getOtherCount();
    /**
     * <pre>
     * Map
     * </pre>
     *
     * <code>map&lt;string, string&gt; other = 7;</code>
     */
    boolean containsOther(
        java.lang.String key);
    /**
     * Use {@link #getOtherMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getOther();
    /**
     * <pre>
     * Map
     * </pre>
     *
     * <code>map&lt;string, string&gt; other = 7;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getOtherMap();
    /**
     * <pre>
     * Map
     * </pre>
     *
     * <code>map&lt;string, string&gt; other = 7;</code>
     */
    /* nullable */
java.lang.String getOtherOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue);
    /**
     * <pre>
     * Map
     * </pre>
     *
     * <code>map&lt;string, string&gt; other = 7;</code>
     */
    java.lang.String getOtherOrThrow(
        java.lang.String key);
  }
  /**
   * <pre>
   * 内部类Person
   * </pre>
   *
   * Protobuf type {@code Person}
   */
  public static final class Person extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Person)
      PersonOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 0,
        /* suffix= */ "",
        Person.class.getName());
    }
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Person() {
      name_ = "";
      address_ = "";
      cars_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.demo.entity.proto.PersonProto.internal_static_Person_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 7:
          return internalGetOther();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.demo.entity.proto.PersonProto.internal_static_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.demo.entity.proto.PersonProto.Person.class, com.demo.entity.proto.PersonProto.Person.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int YEAR_FIELD_NUMBER = 2;
    private int year_ = 0;
    /**
     * <code>int32 year = 2;</code>
     * @return The year.
     */
    @java.lang.Override
    public int getYear() {
      return year_;
    }

    public static final int GENDER_FIELD_NUMBER = 3;
    private boolean gender_ = false;
    /**
     * <code>bool gender = 3;</code>
     * @return The gender.
     */
    @java.lang.Override
    public boolean getGender() {
      return gender_;
    }

    public static final int DATE_FIELD_NUMBER = 4;
    private long date_ = 0L;
    /**
     * <code>int64 date = 4;</code>
     * @return The date.
     */
    @java.lang.Override
    public long getDate() {
      return date_;
    }

    public static final int ADDRESS_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object address_ = "";
    /**
     * <code>string address = 5;</code>
     * @return The address.
     */
    @java.lang.Override
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address_ = s;
        return s;
      }
    }
    /**
     * <code>string address = 5;</code>
     * @return The bytes for address.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CARS_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private java.util.List<com.demo.entity.proto.PersonProto.Car> cars_;
    /**
     * <pre>
     * 数组
     * </pre>
     *
     * <code>repeated .Car cars = 6;</code>
     */
    @java.lang.Override
    public java.util.List<com.demo.entity.proto.PersonProto.Car> getCarsList() {
      return cars_;
    }
    /**
     * <pre>
     * 数组
     * </pre>
     *
     * <code>repeated .Car cars = 6;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.demo.entity.proto.PersonProto.CarOrBuilder> 
        getCarsOrBuilderList() {
      return cars_;
    }
    /**
     * <pre>
     * 数组
     * </pre>
     *
     * <code>repeated .Car cars = 6;</code>
     */
    @java.lang.Override
    public int getCarsCount() {
      return cars_.size();
    }
    /**
     * <pre>
     * 数组
     * </pre>
     *
     * <code>repeated .Car cars = 6;</code>
     */
    @java.lang.Override
    public com.demo.entity.proto.PersonProto.Car getCars(int index) {
      return cars_.get(index);
    }
    /**
     * <pre>
     * 数组
     * </pre>
     *
     * <code>repeated .Car cars = 6;</code>
     */
    @java.lang.Override
    public com.demo.entity.proto.PersonProto.CarOrBuilder getCarsOrBuilder(
        int index) {
      return cars_.get(index);
    }

    public static final int OTHER_FIELD_NUMBER = 7;
    private static final class OtherDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.demo.entity.proto.PersonProto.internal_static_Person_OtherEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> other_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetOther() {
      if (other_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            OtherDefaultEntryHolder.defaultEntry);
      }
      return other_;
    }
    public int getOtherCount() {
      return internalGetOther().getMap().size();
    }
    /**
     * <pre>
     * Map
     * </pre>
     *
     * <code>map&lt;string, string&gt; other = 7;</code>
     */
    @java.lang.Override
    public boolean containsOther(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetOther().getMap().containsKey(key);
    }
    /**
     * Use {@link #getOtherMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getOther() {
      return getOtherMap();
    }
    /**
     * <pre>
     * Map
     * </pre>
     *
     * <code>map&lt;string, string&gt; other = 7;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getOtherMap() {
      return internalGetOther().getMap();
    }
    /**
     * <pre>
     * Map
     * </pre>
     *
     * <code>map&lt;string, string&gt; other = 7;</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getOtherOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetOther().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * Map
     * </pre>
     *
     * <code>map&lt;string, string&gt; other = 7;</code>
     */
    @java.lang.Override
    public java.lang.String getOtherOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetOther().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, name_);
      }
      if (year_ != 0) {
        output.writeInt32(2, year_);
      }
      if (gender_ != false) {
        output.writeBool(3, gender_);
      }
      if (date_ != 0L) {
        output.writeInt64(4, date_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(address_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 5, address_);
      }
      for (int i = 0; i < cars_.size(); i++) {
        output.writeMessage(6, cars_.get(i));
      }
      com.google.protobuf.GeneratedMessage
        .serializeStringMapTo(
          output,
          internalGetOther(),
          OtherDefaultEntryHolder.defaultEntry,
          7);
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, name_);
      }
      if (year_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, year_);
      }
      if (gender_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, gender_);
      }
      if (date_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, date_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(address_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(5, address_);
      }
      for (int i = 0; i < cars_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, cars_.get(i));
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetOther().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        other__ = OtherDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(7, other__);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.demo.entity.proto.PersonProto.Person)) {
        return super.equals(obj);
      }
      com.demo.entity.proto.PersonProto.Person other = (com.demo.entity.proto.PersonProto.Person) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (getYear()
          != other.getYear()) return false;
      if (getGender()
          != other.getGender()) return false;
      if (getDate()
          != other.getDate()) return false;
      if (!getAddress()
          .equals(other.getAddress())) return false;
      if (!getCarsList()
          .equals(other.getCarsList())) return false;
      if (!internalGetOther().equals(
          other.internalGetOther())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + YEAR_FIELD_NUMBER;
      hash = (53 * hash) + getYear();
      hash = (37 * hash) + GENDER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getGender());
      hash = (37 * hash) + DATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDate());
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      if (getCarsCount() > 0) {
        hash = (37 * hash) + CARS_FIELD_NUMBER;
        hash = (53 * hash) + getCarsList().hashCode();
      }
      if (!internalGetOther().getMap().isEmpty()) {
        hash = (37 * hash) + OTHER_FIELD_NUMBER;
        hash = (53 * hash) + internalGetOther().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.demo.entity.proto.PersonProto.Person parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.demo.entity.proto.PersonProto.Person parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.demo.entity.proto.PersonProto.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.demo.entity.proto.PersonProto.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.demo.entity.proto.PersonProto.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.demo.entity.proto.PersonProto.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.demo.entity.proto.PersonProto.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.demo.entity.proto.PersonProto.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.demo.entity.proto.PersonProto.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.demo.entity.proto.PersonProto.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.demo.entity.proto.PersonProto.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.demo.entity.proto.PersonProto.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.demo.entity.proto.PersonProto.Person prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 内部类Person
     * </pre>
     *
     * Protobuf type {@code Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Person)
        com.demo.entity.proto.PersonProto.PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.demo.entity.proto.PersonProto.internal_static_Person_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
          int number) {
        switch (number) {
          case 7:
            return internalGetOther();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
          int number) {
        switch (number) {
          case 7:
            return internalGetMutableOther();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.demo.entity.proto.PersonProto.internal_static_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.demo.entity.proto.PersonProto.Person.class, com.demo.entity.proto.PersonProto.Person.Builder.class);
      }

      // Construct using com.demo.entity.proto.PersonProto.Person.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        name_ = "";
        year_ = 0;
        gender_ = false;
        date_ = 0L;
        address_ = "";
        if (carsBuilder_ == null) {
          cars_ = java.util.Collections.emptyList();
        } else {
          cars_ = null;
          carsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        internalGetMutableOther().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.demo.entity.proto.PersonProto.internal_static_Person_descriptor;
      }

      @java.lang.Override
      public com.demo.entity.proto.PersonProto.Person getDefaultInstanceForType() {
        return com.demo.entity.proto.PersonProto.Person.getDefaultInstance();
      }

      @java.lang.Override
      public com.demo.entity.proto.PersonProto.Person build() {
        com.demo.entity.proto.PersonProto.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.demo.entity.proto.PersonProto.Person buildPartial() {
        com.demo.entity.proto.PersonProto.Person result = new com.demo.entity.proto.PersonProto.Person(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(com.demo.entity.proto.PersonProto.Person result) {
        if (carsBuilder_ == null) {
          if (((bitField0_ & 0x00000020) != 0)) {
            cars_ = java.util.Collections.unmodifiableList(cars_);
            bitField0_ = (bitField0_ & ~0x00000020);
          }
          result.cars_ = cars_;
        } else {
          result.cars_ = carsBuilder_.build();
        }
      }

      private void buildPartial0(com.demo.entity.proto.PersonProto.Person result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.year_ = year_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.gender_ = gender_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.date_ = date_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.address_ = address_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.other_ = internalGetOther();
          result.other_.makeImmutable();
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.demo.entity.proto.PersonProto.Person) {
          return mergeFrom((com.demo.entity.proto.PersonProto.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.demo.entity.proto.PersonProto.Person other) {
        if (other == com.demo.entity.proto.PersonProto.Person.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getYear() != 0) {
          setYear(other.getYear());
        }
        if (other.getGender() != false) {
          setGender(other.getGender());
        }
        if (other.getDate() != 0L) {
          setDate(other.getDate());
        }
        if (!other.getAddress().isEmpty()) {
          address_ = other.address_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (carsBuilder_ == null) {
          if (!other.cars_.isEmpty()) {
            if (cars_.isEmpty()) {
              cars_ = other.cars_;
              bitField0_ = (bitField0_ & ~0x00000020);
            } else {
              ensureCarsIsMutable();
              cars_.addAll(other.cars_);
            }
            onChanged();
          }
        } else {
          if (!other.cars_.isEmpty()) {
            if (carsBuilder_.isEmpty()) {
              carsBuilder_.dispose();
              carsBuilder_ = null;
              cars_ = other.cars_;
              bitField0_ = (bitField0_ & ~0x00000020);
              carsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getCarsFieldBuilder() : null;
            } else {
              carsBuilder_.addAllMessages(other.cars_);
            }
          }
        }
        internalGetMutableOther().mergeFrom(
            other.internalGetOther());
        bitField0_ |= 0x00000040;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                year_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                gender_ = input.readBool();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                date_ = input.readInt64();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 42: {
                address_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 50: {
                com.demo.entity.proto.PersonProto.Car m =
                    input.readMessage(
                        com.demo.entity.proto.PersonProto.Car.parser(),
                        extensionRegistry);
                if (carsBuilder_ == null) {
                  ensureCarsIsMutable();
                  cars_.add(m);
                } else {
                  carsBuilder_.addMessage(m);
                }
                break;
              } // case 50
              case 58: {
                com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
                other__ = input.readMessage(
                    OtherDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableOther().getMutableMap().put(
                    other__.getKey(), other__.getValue());
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int year_ ;
      /**
       * <code>int32 year = 2;</code>
       * @return The year.
       */
      @java.lang.Override
      public int getYear() {
        return year_;
      }
      /**
       * <code>int32 year = 2;</code>
       * @param value The year to set.
       * @return This builder for chaining.
       */
      public Builder setYear(int value) {

        year_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 year = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearYear() {
        bitField0_ = (bitField0_ & ~0x00000002);
        year_ = 0;
        onChanged();
        return this;
      }

      private boolean gender_ ;
      /**
       * <code>bool gender = 3;</code>
       * @return The gender.
       */
      @java.lang.Override
      public boolean getGender() {
        return gender_;
      }
      /**
       * <code>bool gender = 3;</code>
       * @param value The gender to set.
       * @return This builder for chaining.
       */
      public Builder setGender(boolean value) {

        gender_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>bool gender = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearGender() {
        bitField0_ = (bitField0_ & ~0x00000004);
        gender_ = false;
        onChanged();
        return this;
      }

      private long date_ ;
      /**
       * <code>int64 date = 4;</code>
       * @return The date.
       */
      @java.lang.Override
      public long getDate() {
        return date_;
      }
      /**
       * <code>int64 date = 4;</code>
       * @param value The date to set.
       * @return This builder for chaining.
       */
      public Builder setDate(long value) {

        date_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>int64 date = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearDate() {
        bitField0_ = (bitField0_ & ~0x00000008);
        date_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object address_ = "";
      /**
       * <code>string address = 5;</code>
       * @return The address.
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string address = 5;</code>
       * @return The bytes for address.
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string address = 5;</code>
       * @param value The address to set.
       * @return This builder for chaining.
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        address_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>string address = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearAddress() {
        address_ = getDefaultInstance().getAddress();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>string address = 5;</code>
       * @param value The bytes for address to set.
       * @return This builder for chaining.
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        address_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private java.util.List<com.demo.entity.proto.PersonProto.Car> cars_ =
        java.util.Collections.emptyList();
      private void ensureCarsIsMutable() {
        if (!((bitField0_ & 0x00000020) != 0)) {
          cars_ = new java.util.ArrayList<com.demo.entity.proto.PersonProto.Car>(cars_);
          bitField0_ |= 0x00000020;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.demo.entity.proto.PersonProto.Car, com.demo.entity.proto.PersonProto.Car.Builder, com.demo.entity.proto.PersonProto.CarOrBuilder> carsBuilder_;

      /**
       * <pre>
       * 数组
       * </pre>
       *
       * <code>repeated .Car cars = 6;</code>
       */
      public java.util.List<com.demo.entity.proto.PersonProto.Car> getCarsList() {
        if (carsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(cars_);
        } else {
          return carsBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * 数组
       * </pre>
       *
       * <code>repeated .Car cars = 6;</code>
       */
      public int getCarsCount() {
        if (carsBuilder_ == null) {
          return cars_.size();
        } else {
          return carsBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * 数组
       * </pre>
       *
       * <code>repeated .Car cars = 6;</code>
       */
      public com.demo.entity.proto.PersonProto.Car getCars(int index) {
        if (carsBuilder_ == null) {
          return cars_.get(index);
        } else {
          return carsBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * 数组
       * </pre>
       *
       * <code>repeated .Car cars = 6;</code>
       */
      public Builder setCars(
          int index, com.demo.entity.proto.PersonProto.Car value) {
        if (carsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCarsIsMutable();
          cars_.set(index, value);
          onChanged();
        } else {
          carsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 数组
       * </pre>
       *
       * <code>repeated .Car cars = 6;</code>
       */
      public Builder setCars(
          int index, com.demo.entity.proto.PersonProto.Car.Builder builderForValue) {
        if (carsBuilder_ == null) {
          ensureCarsIsMutable();
          cars_.set(index, builderForValue.build());
          onChanged();
        } else {
          carsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 数组
       * </pre>
       *
       * <code>repeated .Car cars = 6;</code>
       */
      public Builder addCars(com.demo.entity.proto.PersonProto.Car value) {
        if (carsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCarsIsMutable();
          cars_.add(value);
          onChanged();
        } else {
          carsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * 数组
       * </pre>
       *
       * <code>repeated .Car cars = 6;</code>
       */
      public Builder addCars(
          int index, com.demo.entity.proto.PersonProto.Car value) {
        if (carsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCarsIsMutable();
          cars_.add(index, value);
          onChanged();
        } else {
          carsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 数组
       * </pre>
       *
       * <code>repeated .Car cars = 6;</code>
       */
      public Builder addCars(
          com.demo.entity.proto.PersonProto.Car.Builder builderForValue) {
        if (carsBuilder_ == null) {
          ensureCarsIsMutable();
          cars_.add(builderForValue.build());
          onChanged();
        } else {
          carsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 数组
       * </pre>
       *
       * <code>repeated .Car cars = 6;</code>
       */
      public Builder addCars(
          int index, com.demo.entity.proto.PersonProto.Car.Builder builderForValue) {
        if (carsBuilder_ == null) {
          ensureCarsIsMutable();
          cars_.add(index, builderForValue.build());
          onChanged();
        } else {
          carsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 数组
       * </pre>
       *
       * <code>repeated .Car cars = 6;</code>
       */
      public Builder addAllCars(
          java.lang.Iterable<? extends com.demo.entity.proto.PersonProto.Car> values) {
        if (carsBuilder_ == null) {
          ensureCarsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, cars_);
          onChanged();
        } else {
          carsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * 数组
       * </pre>
       *
       * <code>repeated .Car cars = 6;</code>
       */
      public Builder clearCars() {
        if (carsBuilder_ == null) {
          cars_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
          onChanged();
        } else {
          carsBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 数组
       * </pre>
       *
       * <code>repeated .Car cars = 6;</code>
       */
      public Builder removeCars(int index) {
        if (carsBuilder_ == null) {
          ensureCarsIsMutable();
          cars_.remove(index);
          onChanged();
        } else {
          carsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * 数组
       * </pre>
       *
       * <code>repeated .Car cars = 6;</code>
       */
      public com.demo.entity.proto.PersonProto.Car.Builder getCarsBuilder(
          int index) {
        return getCarsFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * 数组
       * </pre>
       *
       * <code>repeated .Car cars = 6;</code>
       */
      public com.demo.entity.proto.PersonProto.CarOrBuilder getCarsOrBuilder(
          int index) {
        if (carsBuilder_ == null) {
          return cars_.get(index);  } else {
          return carsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * 数组
       * </pre>
       *
       * <code>repeated .Car cars = 6;</code>
       */
      public java.util.List<? extends com.demo.entity.proto.PersonProto.CarOrBuilder> 
           getCarsOrBuilderList() {
        if (carsBuilder_ != null) {
          return carsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(cars_);
        }
      }
      /**
       * <pre>
       * 数组
       * </pre>
       *
       * <code>repeated .Car cars = 6;</code>
       */
      public com.demo.entity.proto.PersonProto.Car.Builder addCarsBuilder() {
        return getCarsFieldBuilder().addBuilder(
            com.demo.entity.proto.PersonProto.Car.getDefaultInstance());
      }
      /**
       * <pre>
       * 数组
       * </pre>
       *
       * <code>repeated .Car cars = 6;</code>
       */
      public com.demo.entity.proto.PersonProto.Car.Builder addCarsBuilder(
          int index) {
        return getCarsFieldBuilder().addBuilder(
            index, com.demo.entity.proto.PersonProto.Car.getDefaultInstance());
      }
      /**
       * <pre>
       * 数组
       * </pre>
       *
       * <code>repeated .Car cars = 6;</code>
       */
      public java.util.List<com.demo.entity.proto.PersonProto.Car.Builder> 
           getCarsBuilderList() {
        return getCarsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.demo.entity.proto.PersonProto.Car, com.demo.entity.proto.PersonProto.Car.Builder, com.demo.entity.proto.PersonProto.CarOrBuilder> 
          getCarsFieldBuilder() {
        if (carsBuilder_ == null) {
          carsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.demo.entity.proto.PersonProto.Car, com.demo.entity.proto.PersonProto.Car.Builder, com.demo.entity.proto.PersonProto.CarOrBuilder>(
                  cars_,
                  ((bitField0_ & 0x00000020) != 0),
                  getParentForChildren(),
                  isClean());
          cars_ = null;
        }
        return carsBuilder_;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> other_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
          internalGetOther() {
        if (other_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              OtherDefaultEntryHolder.defaultEntry);
        }
        return other_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
          internalGetMutableOther() {
        if (other_ == null) {
          other_ = com.google.protobuf.MapField.newMapField(
              OtherDefaultEntryHolder.defaultEntry);
        }
        if (!other_.isMutable()) {
          other_ = other_.copy();
        }
        bitField0_ |= 0x00000040;
        onChanged();
        return other_;
      }
      public int getOtherCount() {
        return internalGetOther().getMap().size();
      }
      /**
       * <pre>
       * Map
       * </pre>
       *
       * <code>map&lt;string, string&gt; other = 7;</code>
       */
      @java.lang.Override
      public boolean containsOther(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        return internalGetOther().getMap().containsKey(key);
      }
      /**
       * Use {@link #getOtherMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getOther() {
        return getOtherMap();
      }
      /**
       * <pre>
       * Map
       * </pre>
       *
       * <code>map&lt;string, string&gt; other = 7;</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.String, java.lang.String> getOtherMap() {
        return internalGetOther().getMap();
      }
      /**
       * <pre>
       * Map
       * </pre>
       *
       * <code>map&lt;string, string&gt; other = 7;</code>
       */
      @java.lang.Override
      public /* nullable */
java.lang.String getOtherOrDefault(
          java.lang.String key,
          /* nullable */
java.lang.String defaultValue) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetOther().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       * Map
       * </pre>
       *
       * <code>map&lt;string, string&gt; other = 7;</code>
       */
      @java.lang.Override
      public java.lang.String getOtherOrThrow(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetOther().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }
      public Builder clearOther() {
        bitField0_ = (bitField0_ & ~0x00000040);
        internalGetMutableOther().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       * Map
       * </pre>
       *
       * <code>map&lt;string, string&gt; other = 7;</code>
       */
      public Builder removeOther(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        internalGetMutableOther().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
          getMutableOther() {
        bitField0_ |= 0x00000040;
        return internalGetMutableOther().getMutableMap();
      }
      /**
       * <pre>
       * Map
       * </pre>
       *
       * <code>map&lt;string, string&gt; other = 7;</code>
       */
      public Builder putOther(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new NullPointerException("map key"); }
        if (value == null) { throw new NullPointerException("map value"); }
        internalGetMutableOther().getMutableMap()
            .put(key, value);
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <pre>
       * Map
       * </pre>
       *
       * <code>map&lt;string, string&gt; other = 7;</code>
       */
      public Builder putAllOther(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableOther().getMutableMap()
            .putAll(values);
        bitField0_ |= 0x00000040;
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Person)
    }

    // @@protoc_insertion_point(class_scope:Person)
    private static final com.demo.entity.proto.PersonProto.Person DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.demo.entity.proto.PersonProto.Person();
    }

    public static com.demo.entity.proto.PersonProto.Person getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Person>
        PARSER = new com.google.protobuf.AbstractParser<Person>() {
      @java.lang.Override
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Person> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.demo.entity.proto.PersonProto.Person getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CarOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Car)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string color = 2;</code>
     * @return The color.
     */
    java.lang.String getColor();
    /**
     * <code>string color = 2;</code>
     * @return The bytes for color.
     */
    com.google.protobuf.ByteString
        getColorBytes();
  }
  /**
   * <pre>
   * 内部类Car
   * </pre>
   *
   * Protobuf type {@code Car}
   */
  public static final class Car extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Car)
      CarOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 0,
        /* suffix= */ "",
        Car.class.getName());
    }
    // Use Car.newBuilder() to construct.
    private Car(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Car() {
      name_ = "";
      color_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.demo.entity.proto.PersonProto.internal_static_Car_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.demo.entity.proto.PersonProto.internal_static_Car_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.demo.entity.proto.PersonProto.Car.class, com.demo.entity.proto.PersonProto.Car.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COLOR_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object color_ = "";
    /**
     * <code>string color = 2;</code>
     * @return The color.
     */
    @java.lang.Override
    public java.lang.String getColor() {
      java.lang.Object ref = color_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        color_ = s;
        return s;
      }
    }
    /**
     * <code>string color = 2;</code>
     * @return The bytes for color.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getColorBytes() {
      java.lang.Object ref = color_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        color_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, name_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(color_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, color_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, name_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(color_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, color_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.demo.entity.proto.PersonProto.Car)) {
        return super.equals(obj);
      }
      com.demo.entity.proto.PersonProto.Car other = (com.demo.entity.proto.PersonProto.Car) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (!getColor()
          .equals(other.getColor())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + COLOR_FIELD_NUMBER;
      hash = (53 * hash) + getColor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.demo.entity.proto.PersonProto.Car parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.demo.entity.proto.PersonProto.Car parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.demo.entity.proto.PersonProto.Car parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.demo.entity.proto.PersonProto.Car parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.demo.entity.proto.PersonProto.Car parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.demo.entity.proto.PersonProto.Car parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.demo.entity.proto.PersonProto.Car parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.demo.entity.proto.PersonProto.Car parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.demo.entity.proto.PersonProto.Car parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.demo.entity.proto.PersonProto.Car parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.demo.entity.proto.PersonProto.Car parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.demo.entity.proto.PersonProto.Car parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.demo.entity.proto.PersonProto.Car prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 内部类Car
     * </pre>
     *
     * Protobuf type {@code Car}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Car)
        com.demo.entity.proto.PersonProto.CarOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.demo.entity.proto.PersonProto.internal_static_Car_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.demo.entity.proto.PersonProto.internal_static_Car_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.demo.entity.proto.PersonProto.Car.class, com.demo.entity.proto.PersonProto.Car.Builder.class);
      }

      // Construct using com.demo.entity.proto.PersonProto.Car.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        name_ = "";
        color_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.demo.entity.proto.PersonProto.internal_static_Car_descriptor;
      }

      @java.lang.Override
      public com.demo.entity.proto.PersonProto.Car getDefaultInstanceForType() {
        return com.demo.entity.proto.PersonProto.Car.getDefaultInstance();
      }

      @java.lang.Override
      public com.demo.entity.proto.PersonProto.Car build() {
        com.demo.entity.proto.PersonProto.Car result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.demo.entity.proto.PersonProto.Car buildPartial() {
        com.demo.entity.proto.PersonProto.Car result = new com.demo.entity.proto.PersonProto.Car(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.demo.entity.proto.PersonProto.Car result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.color_ = color_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.demo.entity.proto.PersonProto.Car) {
          return mergeFrom((com.demo.entity.proto.PersonProto.Car)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.demo.entity.proto.PersonProto.Car other) {
        if (other == com.demo.entity.proto.PersonProto.Car.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getColor().isEmpty()) {
          color_ = other.color_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                color_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object color_ = "";
      /**
       * <code>string color = 2;</code>
       * @return The color.
       */
      public java.lang.String getColor() {
        java.lang.Object ref = color_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          color_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string color = 2;</code>
       * @return The bytes for color.
       */
      public com.google.protobuf.ByteString
          getColorBytes() {
        java.lang.Object ref = color_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          color_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string color = 2;</code>
       * @param value The color to set.
       * @return This builder for chaining.
       */
      public Builder setColor(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        color_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string color = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearColor() {
        color_ = getDefaultInstance().getColor();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string color = 2;</code>
       * @param value The bytes for color to set.
       * @return This builder for chaining.
       */
      public Builder setColorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        color_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Car)
    }

    // @@protoc_insertion_point(class_scope:Car)
    private static final com.demo.entity.proto.PersonProto.Car DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.demo.entity.proto.PersonProto.Car();
    }

    public static com.demo.entity.proto.PersonProto.Car getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Car>
        PARSER = new com.google.protobuf.AbstractParser<Car>() {
      @java.lang.Override
      public Car parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Car> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Car> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.demo.entity.proto.PersonProto.Car getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Person_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Person_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Person_OtherEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Person_OtherEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Car_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Car_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014person.proto\"\270\001\n\006Person\022\014\n\004name\030\001 \001(\t\022" +
      "\014\n\004year\030\002 \001(\005\022\016\n\006gender\030\003 \001(\010\022\014\n\004date\030\004 " +
      "\001(\003\022\017\n\007address\030\005 \001(\t\022\022\n\004cars\030\006 \003(\0132\004.Car" +
      "\022!\n\005other\030\007 \003(\0132\022.Person.OtherEntry\032,\n\nO" +
      "therEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028" +
      "\001\"\"\n\003Car\022\014\n\004name\030\001 \001(\t\022\r\n\005color\030\002 \001(\tB$\n" +
      "\025com.demo.entity.protoB\013PersonProtob\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Person_descriptor,
        new java.lang.String[] { "Name", "Year", "Gender", "Date", "Address", "Cars", "Other", });
    internal_static_Person_OtherEntry_descriptor =
      internal_static_Person_descriptor.getNestedTypes().get(0);
    internal_static_Person_OtherEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Person_OtherEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_Car_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Car_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Car_descriptor,
        new java.lang.String[] { "Name", "Color", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
