spring:
  devtools:
    restart:
      enabled: true
  servlet:
    multipart:
      max-file-size: 4GB
      max-request-size: 4GB
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password:
      timeout: 10s

#server:
#  port: 8081

mqtt:
  uri: tcp://127.0.0.1:1883
  connection-timeout: 30
  keep-alive-interval: 60
  clean-session: false
  automatic-reconnect: true

logging:
  level:
    root: info
  file:
    name: /log/demo-mqtt-cluster.log
